# Generated by Django 5.1 on 2026-01-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_fundraiser_owner_pledge_supporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
